blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.all_post, name='all_post'),
    path('<slug>/', views.post, name='post'),
]

contact/urls.py
from django.urls import path

from contact import views

app_name = "contact"

urlpatterns = [
    # path('', views.contact_form, name='contact_form')
    path('', views.CustomerAddContact.as_view(), name='contact_form')
]

wedding_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views
from wedding_blog import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
    # path('froala_editor/', include('froala_editor.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django_extensions.db.fields import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from froala_editor.fields import FroalaField


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=250, blank=False)
    keywords = models.CharField(max_length=250, blank=False)
    body = FroalaField()
    slug = AutoSlugField(populate_from='title')
    image = models.FileField(upload_to='posts', blank=False)
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def slugify_function(self, content):
        return content.replace(' ', '-').lower()

    def get_absolute_url(self):
        return reverse('blog:post', args={self.slug})

    def __str__(self):
        return '"{title}" '.format(title=self.title)

contact/models.py
from django.db import models


class Contact(models.Model):
    user = models.CharField(max_length=100, blank=False)
    phone = models.CharField(max_length=100, blank=False)
    message = models.CharField(max_length=256, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '"{user}"'.format(user=self.user)

contact/forms.py
from django.forms import ModelForm
from contact.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['user', 'phone', 'message']
        labels = {
            'user': 'Имя',
            'phone': 'Телефон',
            'message': 'Сообщение',
        }

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from blog.models import Post
from contact.forms import ContactForm

NUM_OF_POSTS = 5


def index(request):
    contact_form = ContactForm()
    return render(request, 'index.html', {'contact_form': contact_form})


def all_post(request):
    contact_form = ContactForm()
    post_list = Post.objects.all()
    post_list = post_list.order_by('-pub_date')
    paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'blog.html', {'posts': post_list, 'contact_form': contact_form})


def post(request, slug):
    contact_form = ContactForm()
    try:
        post = Post.objects.get(slug=slug)
    except Exception as e:
        raise e
    return render(request, 'post.html', {'post': post, 'contact_form': contact_form})

contact/views.py
from django.http import Http404, JsonResponse
from contact.forms import ContactForm
from contact.serializers import ContactSerializer
from contact.telegram_notification import send_message
from rest_framework.views import APIView
from django.middleware.csrf import get_token


# def contact_form(request):
#     if request.is_ajax():
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             context = {'result': 'success', 'message': '<strong>Ваша заявка принята.</strong> '
#                                                        'Мы свяжимся с Вами в ближайшее время!'}
#             name = request.POST.get("user")
#             phone = request.POST.get("phone")
#             message = request.POST.get("message")
#             message_text = "Новый запрос на сайте " + "\n Имя " + name + "\n Телефон " + phone + "\n Сообщение: " + message
#             send_message(message_text)
#         else:
#             print(form)
#             context = {'result': 'error'}
#         return JsonResponse(context)
#     else:
#         raise Http404

class CustomerAddContact(APIView):
    """
    DRF view API for contact form
    :param request: user, phone, message
    :return: success
    """
    def post(self, request):
        serializer = ContactSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            context = {'result': 'success',
                       'message': '<strong>Ваша заявка принята.</strong> '
                                  'Мы свяжемся с Вами в ближайшее время!'}
            name = request.data.get("user")
            phone = request.data.get("phone")
            message = request.data.get("message")
            message_text = "Новый запрос на сайте " + "\n Имя: " + name + "\n Телефон: " + phone + "\n Сообщение: " + message
            send_message(message_text)
        else:
            context = {'result': 'error'}
        return JsonResponse(context)

blog/templates/base.html
{% load static %}
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-157438207-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-157438207-1');
    </script>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'media/img/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="{% block description %}Ведущая Анастасия Кись. Узнать подробности о Ведущей и забронировать его на мероприятие можно на сайте!{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}Ведущая Анастасия Кись, ведущиая, лучшая ведущая, ведущая мероприятий, ведущая корпоративов, ведущая свадеб{% endblock keywords %}">
    <meta name="author" content="Ведущая Анастасия Кись">
    <title>{% block title %}Ведущая Анастасия Кись{% endblock title %}</title>

    <link href="{% static 'blog/css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <link href="{% static 'blog/css/owl.carousel.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/owl.theme.default.min.css' %}">
    <link href="{% static 'blog/css/agency.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="#" />
</head>
<body>

{% include 'nav.html' %}

{% block content %}{% endblock %}

 {% include 'footer.html' %}

 {% include 'contact_form.html' %}

<div class="email-bt">
    <button class="btn" data-toggle="modal"  data-target="#contact_form_id"><i class="fa fa-envelope"></i></button>
</div>

</body>
<script src="{% static 'blog/js/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/css/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'blog/js/jquery-easing/jquery.easing.min.js' %}"></script>

<script src="{% static 'blog/js/jqBootstrapValidation.js' %}"></script>
<script src="{% static 'blog/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'blog/js/fslightbox.js' %}"></script>
<!-- Contact form JavaScript -->
<script src="{% static 'blog/js/contact.form.js' %}"></script>
<!-- My JavaScript -->
<script src="{% static 'blog/js/agency.js' %}"></script>
</html>

blog/templates/blog.html
{% extends "base.html" %}
{% load static %}
{% block title %}Блог Анастасии Кись в котором я расскажу об основных моментах, лучших практиках, поделюсь последними трендами проведения свадеб, выездных церемоний, кооперативах  {% endblock %}
{% block description %}блог, корпаративы, выезндные церемонии{% endblock %}
{% block keywords %}блог, корпоративы, выездные церемонии{% endblock %}
{% block content %}

<section class="page-section mt-50" id="all_post">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Мой блог</h2>
                <h3 class="section-subheading text-muted">В блоге я пишу свои мысли, делюсь полезными советами</h3>
            </div>
        </div>
         {% for post in posts %}
            <!-- Grid row -->
            <div class="row align-items-center mt-5">
                <!-- Grid column -->
                <div class="col-lg-5 col-xl-4 ">
                    <!-- Featured image -->
                    <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
                        <img class="img-fluid" src="{{ post.image.url }}" alt="Sample image">
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                </div>
                <!-- Grid column -->
                <div class="col-lg-7 col-xl-8">
                    <!-- Post title -->
                    <h4 class="font-weight-bold mb-3"><strong>{{ post.title }}</strong></h4>
                    <!-- Excerpt -->
                    <p class="dark-grey-text">{{ post.body|truncatechars:155 }}</p>
                    <!-- Post data -->
                    <p>Автор: <a class="font-weight-bold">Кись Анастасия</a>, {{ post.pub_date }}</p>
                    <!-- Read more button -->
                    <a class="float-right btn btn-primary"
                       href="{{ post.get_absolute_url }}">Подробней</a>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
            <hr class="mt-5">
        {% endfor %}


        <!-- Pagination -->
        <div class="pagination">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            {% if posts.paginator.num_pages > 1 %}
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            {% endif %}

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/contact_form.html
{% load crispy_forms_tags %}

<div id="contact_form_alert"></div>
<div class="modal fade" id="contact_form_id" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form class="needs-validation" id="contact_form" action="" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">ОСТАВИТЬ ЗАЯВКУ:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ contact_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-primary" id="submitForm">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>

blog/templates/footer.html
<!-- Footer -->
<footer class="footer page-footer font-small mdb-color lighten-3 pt-4" id="contact">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1 d-none d-md-block">
                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
                <p>Here you can use rows and columns to organize your footer content.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit amet numquam iure provident voluptate
                    esse
                    quasi, veritatis totam voluptas nostrum.</p>
            </div>
            <!-- Grid column -->
            <!--      <hr class="clearfix w-100 d-md-none">-->
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1 d-none d-md-block">
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mb-4">About</h5>
                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="#!">PROJECTS</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">ABOUT US</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">BLOG</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">AWARDS</a>
                        </p>
                    </li>
                </ul>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-sm-6 col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>
                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="mailto: abc@example.com"><i class="fas fa-envelope mr-3"></i> info@example.com</a>
                    </li>
                    <li>
                        <p>
                            <a href="tel:+380673406767"> <i class="fas fa-phone mr-3"></i> +380634183223</a>
                    </li>
                    <li>
                        <p>
                            <a class="telegram-ic" a title="Telegram" href="tg://resolve?domain=+380634183223"><i
                                    class="fab fa-lg fa-telegram mr-3"></i> +380634183223</a>
                    </li>
                    <li>
                        <p>
                            <a class="viber-ic " href="viber://chat?number=+380634183223"><i
                                    class="fab fa-lg fa-viber mr-3"></i> +380634183223</a>
                    </li>
                    <li>
                        <p>
                            <a class="whatsapp-ic " href="https://api.whatsapp.com/send?phone=+380634183223"><i
                                    class="fab fa-lg fa-whatsapp mr-3"></i> +380634183223</a>
                    </li>
                </ul>
            </div>
            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-sm-6 col-md-2 col-lg-2 text-center mx-auto my-4">
                <!-- Social buttons -->
                <h5 class="font-weight-bold text-uppercase mb-4 d-none d-md-block">Follow Us</h5>
                <ul class="list-unstyled social-buttons">
                    <li>
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
    <!-- Footer Links -->
</footer>
<!-- Footer -->

blog/templates/nav.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}#page-top"><i class="fab fa-2x fa-korvue"></i></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'index' %}#about" data-target="#about">Обо мне</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'index' %}#ivent" data-target="#ivent">Мероприятия</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'index' %}#portfolio" data-target="#portfolio">Портфолио</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'index' %}#contact" data-target="#contact">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'blog:all_post' %}" data-target="#all_post">Блог</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog/templates/post.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block description %}{{ post.description }}{% endblock %}
{% block keywords %}{{ post.keywords }}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <!--Section: Content-->
        <section class="mx-md-5 dark-grey-text">
            <!-- Grid row -->
            <div class="row">
                <!-- Grid column -->
                <div class="col-md-12">
                    <!-- Card -->
                    <div class="card card-cascade wider reverse">
                        <!-- Card image -->
                        <div class="view view-cascade overlay">
                            <img class="card-img-top" src="{{ post.image.url }}"
                                 alt="Sample image">
                            <a href="#!">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                        <!-- Card content -->
                        <div class="card-body card-body-cascade text-center">
                            <h3 class="font-weight-bold"><a>{{ post.title }}</a></h3>
                            <p>Автор: <a><strong>Анастасия Кись</strong></a>, {{ post.pub_date }}</p>
                        </div>
                        <!-- Card content -->
                    </div>
                    <!-- Card -->
                    <!-- Excerpt -->
                    <div class="mt-5">
                        {% autoescape off %}
                            {{ post.body }}
                        {% endautoescape %}
                    </div>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
            <hr>
        </section>
        <!--Section: Content-->
    </div>
{% endblock %}